routes/web.php
<?php
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\MailController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employees', EmployeeController::class)->middleware(['auth','isAdmin']);
Route::resource('departments', DepartmentController::class)->middleware(['auth','isAdmin']);
Route::resource('positions', \App\Http\Controllers\PositionController::class)->middleware(['auth','isAdmin']);

Auth::routes();

Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('export',[EmployeeController::class,'exportEmployee'])->name('export');

Route::get('users-export', [UserController::class, 'export'])->name('user.export');

Route::get('users', [UserController::class,'index'])->name('user.index')->middleware(['auth','isAdmin']);
Route::get('users/create', [UserController::class,'create'])->name('user.create')->middleware(['auth','isAdmin']);
Route::post('users/store', [UserController::class,'store'])->name('user.store')->middleware(['auth','isAdmin']);
Route::delete('users/{user}', [UserController::class,'destroy'])->name('user.destroy')->middleware(['auth','isAdmin']);

app/Models/Employee.php
<?php

namespace App\Models;
use App\Models\User;
use App\Models\Department;
use App\Models\Position;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $table = 'employees';

    protected $fillable = [
        'name',
        'phone',
        'email',
        'salary',
        'user_id',
        'department_id',
        'position_id'
    ];
    
    public function department()
    {
        return $this->belongsTo(Department::class,'department_id','id');
    }
    public function position()
    {
        return $this->belongsTo(Position::class,'position_id','id');
    }
    public function user()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Maatwebsite\Excel\Facades\Excel;
use App\Exports\EmployeeExport;
use App\Http\Requests\EmployeeRequest;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Position;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::with(['department','position','user'])->paginate(5);
        return view('employees.index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        $users = User::all();
        $positions = Position::all();
        return view('employees.create',compact([
            'departments',
            'users',
            'positions'
        ]));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        Employee::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'salary' => $request->salary,
            'department_id' => $request->department_id,
            'user_id' => $request->user_id,
            'position_id' => $request->position_id,
        ]);
        return redirect(route('employees.index'))->with('message', 'Employee Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $departments = Department::all();
        $users = User::all();
        $positions = Position::all();
        return view('employees.edit',compact([
            'departments',
            'users',
            'positions',
            'employee'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $employee->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'salary' => $request->salary,
            'department_id' => $request->department_id,
            'user_id' => $request->user_id,
            'position_id' => $request->position_id,
        ]);
        return redirect(route('employees.index'))->with('message', 'Employee Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect(route('employees.index'))->with('message', 'Employee Deleted');
    }

    public function exportEmployee()
    {
        return Excel::download(new EmployeeExport, 'employee.xlsx');
    }
}

resources/views/employees/create.blade.php
@extends('common.app')
@section('contents')
@include('components.form_employee')
@endsection

resources/views/employees/edit.blade.php
@extends('common.app')
@section('contents')
<div id="kt_content_container" class="container-xxl">
    <form action="{{ route('employees.update', $employee->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Name</label>
            <input type="text" name="name" value="{{ $employee->name }}"  class="form-control w-75"/>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Email</label>
            <input type="text" name="email" value="{{ $employee->email }}"  class="form-control w-75"/>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Phone</label>
            <input type="text" name="phone" value="{{ $employee->phone }}"  class="form-control w-75"/>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Salary</label>
            <input type="text" name="salary" value="{{ $employee->salary }}"  class="form-control w-75"/>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Department</label>
            <select name="department_id" class="form-control w-75">
                @foreach ($departments as $department)
                    <option value="{{ $department->id }}"  {{ $employee->department_id === $department->id ? 'selected' : '' }}>
                        {{ $department->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">User</label>
            <select name="user_id" class="form-control w-75">
                @foreach ($users as $user)
                    <option value="{{ $user->id }}" {{ $employee->user_id === $user->id ? 'selected' : '' }}>
                        {{ $user->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="d-flex flex-column text-dark fw-bolder fs-3 mb-0 fs-5 fw-bold" style="padding-left: 7px;" for="">Position</label>
            <select name="position_id" class="form-control w-75">
                @foreach ($positions as $position)
                    <option value="{{ $position->id }}"  {{ $employee->position_id === $position->id ? 'selected' : '' }}>
                        {{ $position->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="mt-3 btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('common.app')
@section('contents')
 <!--begin::Content-->
 <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Post-->
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <!--begin::Row-->
            <!--end::Row-->
            <!--begin::Tables Widget 9-->
            <div class="card mb-5 mb-xl-8">
                <!--begin::Header-->
                <div class="card-header border-0 pt-5">
                    <h3 class="card-title align-items-start flex-column">
                        <span class="card-label fw-bolder fs-3 mb-1">Employees List</span>
                    </h3>
                    <div  style="margin-left: 500px;" title="Click to add a new Employee">
                        <a href="{{ route('export') }}" name="" class="btn btn-sm btn-light btn-active-primary" >
                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
                            <!--end::Svg Icon-->Export Exel
                        </a>
                    </div>
                    <div title="Click to add a new Employee">
                        <a href="{{ route('employees.create') }}" class="btn btn-sm btn-light btn-active-primary" >
                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
                            <span class="svg-icon svg-icon-3">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1" transform="rotate(-90 11.364 20.364)" fill="black" />
                                    <rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="black" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->New Employee
                        </a>
                    </div>
                </div>
                <!--end::Header-->
                @if (session('message'))
                <div class="alert alert-success">{{ session('message') }}</div>
            @endif
                <!--begin::Body-->
                <div class="card-body py-3">
                    <!--begin::Table container-->
                    <div class="table-responsive">
                        <!--begin::Table-->
                        <!--begin::Table-->
                        <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                            <!--begin::Table head-->
                            <thead>
                                <tr class="fw-bolder text-muted">
                                    <th class="w-25px">
                                    <div class="form-check form-check-sm form-check-custom form-check-solid">
                                        <input class="form-check-input widget-9-check" type="checkbox" value="1">
                                    </div>
                                    </th>
                                    <th class="min-w-120px">FullName</th>
                                    <th class="min-w-120px">Email</th>
                                    <th class="min-w-120px">Phone</th>
                                    <th class="min-w-120px">Salary</th>
                                    <th class="min-w-120px">Department</th>
                                    <th class="min-w-120px">Position</th>
                                    <th class="min-w-120px">User</th>
                                    <th class="min-w-100px text-end">Actions</th>
                                </tr>
                            </thead>
                            <!--end::Table head-->
                            <!--begin::Table body-->
                                <tbody>
                                    @foreach ($employees as $employee)
                                    <tr>
                                        <td>
                                            <div class="form-check form-check-sm form-check-custom form-check-solid">
                                                <input class="form-check-input widget-9-check" type="checkbox" value="1">
                                            </div>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->name }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->email }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->phone }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->salary }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->department->name }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->position->name }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="text-dark fw-bolder fs-6">{{ $employee->user->name }}</a>
                                        </td>
                                        <td>
                                            <form action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                                <div class="d-flex justify-content-end flex-shrink-0">
                                                    <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1">
                                                        <!--begin::Svg Icon | path: icons/duotune/art/art005.svg-->
                                                        <span class="svg-icon svg-icon-3">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                                <path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="black"></path>
                                                                <path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="black"></path>
                                                            </svg>
                                                        </span>
                                                        <!--end::Svg Icon-->
                                                    </a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" onclick="return confirm('Bạn có chắc chắn xóa nhân viên không?')" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm">
                                                        <!--begin::Svg Icon | path: icons/duotune/general/gen027.svg-->
                                                        <span class="svg-icon svg-icon-3">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                                <path d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z" fill="black"></path>
                                                                <path opacity="0.5" d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z" fill="black"></path>
                                                                <path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z" fill="black"></path>
                                                            </svg>
                                                        </span>
                                                        <!--end::Svg Icon-->
                                                    </button>
                                                </div>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            <!--end::Table body-->
                        </table>
                        <!--end::Table-->
                        <!--end::Table-->
                    </div>
                    <!--end::Table container-->
                </div>
                <!--begin::Body-->
            </div>
            <!--end::Tables Widget 9-->
            <div>{{ $employees->links() }}</div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Post-->
</div>
<!--end::Content-->
@endsection